name: Build Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          # Removed cache to avoid conflicts

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Create .npmrc for legacy peer deps
        run: echo "legacy-peer-deps=true" > .npmrc

      - name: Install dependencies with legacy peer deps
        run: npm ci --legacy-peer-deps

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Clear Expo cache
        run: npx expo install --fix

      - name: Prebuild Android with clean cache
        run: npx expo prebuild --platform android --clean

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
